[build]
  command = "./netlify-build.sh"
  publish = "dist"
  functions = "netlify/functions"

# Netlify Functions are handled automatically, no need to redirect them
# The previous redirect was causing an error because paths starting with /.netlify are reserved

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://gsuiserbzoebcdptglzm.supabase.co wss://gsuiserbzoebcdptglzm.supabase.co https://api.deepseek.com https://data-api.coindesk.com https://testnet.binance.vision https://testnet.binancefuture.com wss://testnet.binancefuture.com https://polyfill.io; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://polyfill.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; manifest-src 'self';"

# Environment variable configuration
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
